# Generated by Django 4.2.7 on 2023-11-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='theatrescreen',
            field=models.CharField(max_length=100),
        ),
    ]
