# Generated by Django 4.2.7 on 2023-11-28 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_movie_theatrescreen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screename', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='theatrescreen',
        ),
        migrations.AddField(
            model_name='movie',
            name='screen',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='booking.screen'),
        ),
    ]
