# Generated by Django 4.2.7 on 2023-11-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_seat_alter_booking_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='username',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
