# Generated by Django 4.2.7 on 2023-11-29 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.register'),
        ),
    ]
